// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldWideBank;

namespace WorldWideBank.Migrations
{
    [DbContext(typeof(WorldWideBankContext))]
    [Migration("20200330040023_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.3");

            modelBuilder.Entity("WorldWideBank.Models.Account", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Number");

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WorldWideBank.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WorldWideBank.Models.Account", b =>
                {
                    b.HasOne("WorldWideBank.Models.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId");

                    b.OwnsOne("WorldWideBank.Models.Money", "Balance", b1 =>
                        {
                            b1.Property<string>("AccountNumber")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Amount")
                                .HasColumnType("REAL");

                            b1.Property<string>("Currency")
                                .HasColumnType("TEXT");

                            b1.HasKey("AccountNumber");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountNumber");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
